on: [push]
name: Backward compatibility check

jobs:
  bc-check:
    name: Backward compatibility check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Fix for: https://github.com/actions/runner/issues/2033
      - name: Mark repository as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
