name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'composer.json'
      - 'phpunit.xml.dist'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'composer.json'
      - 'phpunit.xml.dist'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['7.4', '8.0', '8.1']
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    env:
      extensions: dom, curl, mbstring, fileinfo
      key: cache-v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup extensions cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}-${{ env.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          coverage: xdebug
          ini-values: xdebug.overload_var_dump=1
          tools: prestissimo

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist -n --no-suggest --no-progress

#      - name: Execute tests
#        run: vendor/bin/phpunit --verbose